"""Authoritative Anomaly Taxonomy Registry for ClaimIQ Phase 4 (E001–E067)."""

from typing import Dict, List, Optional
from generator.injector.models import (
    SeverityLevel,
    AnomalyCategory,
    AnomalyDefinition,
)

TAXONOMY: Dict[str, AnomalyDefinition] = {
    # --------------------------------------------------------------------------
    # CATEGORY 1: COMPLETENESS / MISSING DATA (E001–E010)
    # --------------------------------------------------------------------------
    "E001": AnomalyDefinition(
        code="E001",
        category=AnomalyCategory.COMPLETENESS,
        name="Missing Patient Demographic Field",
        description="Patient address state or optional demographic is nullified.",
        severity=SeverityLevel.LOW,
        target_table="patients",
        target_column="address_state",
        expected_rule_category="Completeness",
        mutation_strategy="Set address_state to empty/null representation",
        expected_violation="Mandatory/expected patient geographic attribute is missing",
    ),
    "E002": AnomalyDefinition(
        code="E002",
        category=AnomalyCategory.COMPLETENESS,
        name="Missing Provider Facility Relationship",
        description="Provider facility assignment is cleared to NULL.",
        severity=SeverityLevel.MEDIUM,
        target_table="providers",
        target_column="facility_id",
        expected_rule_category="Completeness",
        mutation_strategy="Update facility_id = NULL for hospital/clinic provider",
        expected_violation="Provider missing healthcare facility association",
    ),
    "E003": AnomalyDefinition(
        code="E003",
        category=AnomalyCategory.COMPLETENESS,
        name="Missing Policy Group Number",
        description="Commercial policy group number cleared to NULL.",
        severity=SeverityLevel.LOW,
        target_table="patient_coverage",
        target_column="group_number",
        expected_rule_category="Completeness",
        mutation_strategy="Set group_number = NULL on commercial coverage",
        expected_violation="Missing group identification on commercial policy",
    ),
    "E004": AnomalyDefinition(
        code="E004",
        category=AnomalyCategory.COMPLETENESS,
        name="Missing Claim Line Procedure Description",
        description="Procedure description is cleared to NULL on itemized claim line.",
        severity=SeverityLevel.LOW,
        target_table="claim_lines",
        target_column="procedure_description",
        expected_rule_category="Completeness",
        mutation_strategy="Set procedure_description = NULL",
        expected_violation="Claim service line missing narrative procedure description",
    ),
    "E005": AnomalyDefinition(
        code="E005",
        category=AnomalyCategory.COMPLETENESS,
        name="Missing Inpatient Encounter Discharge Date",
        description="Inpatient hospitalization discharge date cleared to NULL.",
        severity=SeverityLevel.MEDIUM,
        target_table="encounters",
        target_column="discharge_date",
        expected_rule_category="Completeness",
        mutation_strategy="Set discharge_date = NULL on Inpatient Hospital encounter",
        expected_violation="Inpatient clinical encounter missing discharge timestamp",
    ),
    "E006": AnomalyDefinition(
        code="E006",
        category=AnomalyCategory.COMPLETENESS,
        name="Missing Adjudication Date on Finalized Claim",
        description="Adjudication date cleared to NULL on Paid/Partially Paid claim.",
        severity=SeverityLevel.HIGH,
        target_table="claims",
        target_column="adjudication_date",
        expected_rule_category="Completeness",
        mutation_strategy="Set adjudication_date = NULL on Paid claim",
        expected_violation="Finalized adjudicated claim missing adjudication date",
    ),
    "E007": AnomalyDefinition(
        code="E007",
        category=AnomalyCategory.COMPLETENESS,
        name="Missing Adjustment Description",
        description="Adjustment narrative description cleared to NULL.",
        severity=SeverityLevel.LOW,
        target_table="adjustments",
        target_column="adjustment_description",
        expected_rule_category="Completeness",
        mutation_strategy="Set adjustment_description = NULL",
        expected_violation="Financial adjustment missing explanatory description",
    ),
    "E008": AnomalyDefinition(
        code="E008",
        category=AnomalyCategory.COMPLETENESS,
        name="Missing Status Transition Reason",
        description="Claim status history record cleared of transition reason.",
        severity=SeverityLevel.LOW,
        target_table="claim_status_history",
        target_column="transition_reason",
        expected_rule_category="Completeness",
        mutation_strategy="Set transition_reason = NULL on status history",
        expected_violation="Audit trail missing status change justification",
    ),
    "E009": AnomalyDefinition(
        code="E009",
        category=AnomalyCategory.COMPLETENESS,
        name="Missing Coverage Termination Date",
        description="Patient coverage policy left open-ended when expected terminated.",
        severity=SeverityLevel.LOW,
        target_table="patient_coverage",
        target_column="termination_date",
        expected_rule_category="Completeness",
        mutation_strategy="Set termination_date = NULL on secondary policy",
        expected_violation="Terminated coverage record missing termination date",
    ),
    "E010": AnomalyDefinition(
        code="E010",
        category=AnomalyCategory.COMPLETENESS,
        name="Missing Encounter Secondary Diagnosis",
        description="Encounter secondary diagnosis record removed or cleared.",
        severity=SeverityLevel.MEDIUM,
        target_table="encounter_diagnoses",
        target_column="diagnosis_description",
        expected_rule_category="Completeness",
        mutation_strategy="Set diagnosis_description = NULL on secondary diagnosis",
        expected_violation="Encounter diagnosis record missing narrative description",
    ),

    # --------------------------------------------------------------------------
    # CATEGORY 2: DUPLICATION / UNIQUENESS (E011–E015)
    # --------------------------------------------------------------------------
    "E011": AnomalyDefinition(
        code="E011",
        category=AnomalyCategory.DUPLICATION,
        name="Duplicate Claim Header",
        description="Duplicate claim header with matching patient, provider, DOS, CPT, and billed total.",
        severity=SeverityLevel.HIGH,
        target_table="claims",
        target_column="claim_reference",
        expected_rule_category="Uniqueness",
        mutation_strategy="Insert exact clone of existing claim under new distinct claim_ref",
        expected_violation="Potential duplicate billing on identical patient, provider, and DOS",
    ),
    "E012": AnomalyDefinition(
        code="E012",
        category=AnomalyCategory.DUPLICATION,
        name="Duplicate Claim Line",
        description="Duplicate claim line with identical CPT code and amount within same claim.",
        severity=SeverityLevel.HIGH,
        target_table="claim_lines",
        target_column="cpt_code",
        expected_rule_category="Uniqueness",
        mutation_strategy="Insert clone of service line on same claim with next line_number",
        expected_violation="Duplicate service line billed within a single claim",
    ),
    "E013": AnomalyDefinition(
        code="E013",
        category=AnomalyCategory.DUPLICATION,
        name="Duplicate Payment Transaction",
        description="Duplicate payment transaction allocated to the same claim.",
        severity=SeverityLevel.HIGH,
        target_table="payments",
        target_column="paid_amount",
        expected_rule_category="Uniqueness",
        mutation_strategy="Insert second payment for claim with new payment_reference",
        expected_violation="Duplicate payment disbursement on single claim",
    ),
    "E014": AnomalyDefinition(
        code="E014",
        category=AnomalyCategory.DUPLICATION,
        name="Duplicate Remittance Trace Number",
        description="Duplicate EFT/Check trace number across remittances.",
        severity=SeverityLevel.MEDIUM,
        target_table="remittances",
        target_column="check_trace_number",
        expected_rule_category="Uniqueness",
        mutation_strategy="Mutate check_trace_number to match an existing remittance trace",
        expected_violation="Duplicate payment check trace number detected",
    ),
    "E015": AnomalyDefinition(
        code="E015",
        category=AnomalyCategory.DUPLICATION,
        name="Duplicate Clinical Encounter",
        description="Duplicate clinical encounter on identical DOS for same patient and provider.",
        severity=SeverityLevel.HIGH,
        target_table="encounters",
        target_column="encounter_reference",
        expected_rule_category="Uniqueness",
        mutation_strategy="Insert duplicate encounter on same DOS, patient, and provider",
        expected_violation="Duplicate clinical encounter for same patient on same date",
    ),

    # --------------------------------------------------------------------------
    # CATEGORY 3: REFERENTIAL / CROSS-ENTITY MISMATCHES (E016–E022)
    # --------------------------------------------------------------------------
    "E016": AnomalyDefinition(
        code="E016",
        category=AnomalyCategory.REFERENTIAL,
        name="Provider Facility State Mismatch",
        description="Provider associated with facility in a disjoint state.",
        severity=SeverityLevel.MEDIUM,
        target_table="providers",
        target_column="facility_id",
        expected_rule_category="Referential Integrity",
        mutation_strategy="Reassign facility_id to facility in completely different state",
        expected_violation="Provider practicing at facility in non-licensed state",
    ),
    "E017": AnomalyDefinition(
        code="E017",
        category=AnomalyCategory.REFERENTIAL,
        name="Payer Insurance Plan Mismatch",
        description="Claim billed to Payer A using insurance plan belonging to Payer B.",
        severity=SeverityLevel.HIGH,
        target_table="claims",
        target_column="payer_id",
        expected_rule_category="Referential Integrity",
        mutation_strategy="Update claims.payer_id to another payer while coverage plan belongs to original",
        expected_violation="Claim billed to payer discordant with patient insurance plan",
    ),
    "E018": AnomalyDefinition(
        code="E018",
        category=AnomalyCategory.REFERENTIAL,
        name="Encounter Provider Specialty Mismatch",
        description="Inpatient hospitalization billed by non-hospital specialty (e.g. Dermatology).",
        severity=SeverityLevel.MEDIUM,
        target_table="encounters",
        target_column="provider_id",
        expected_rule_category="Referential Integrity",
        mutation_strategy="Assign dermatologist or non-inpatient provider to Inpatient Hospital encounter",
        expected_violation="Rendering provider specialty incompatible with encounter setting",
    ),
    "E019": AnomalyDefinition(
        code="E019",
        category=AnomalyCategory.REFERENTIAL,
        name="Patient Policy Payer Mismatch",
        description="Claim submitted to a payer for which the patient has no active policy.",
        severity=SeverityLevel.HIGH,
        target_table="claims",
        target_column="payer_id",
        expected_rule_category="Referential Integrity",
        mutation_strategy="Update claims.payer_id to a payer not matching patient coverage",
        expected_violation="Claim payer has no matching active policy for billed patient",
    ),
    "E020": AnomalyDefinition(
        code="E020",
        category=AnomalyCategory.REFERENTIAL,
        name="Claim Line Cross-Claim Linkage",
        description="Claim line associated with a different claim than encounter context.",
        severity=SeverityLevel.HIGH,
        target_table="claim_lines",
        target_column="claim_id",
        expected_rule_category="Referential Integrity",
        mutation_strategy="Reassign claim_lines.claim_id to an unrelated claim",
        expected_violation="Claim line belongs to discordant parent claim context",
    ),
    "E021": AnomalyDefinition(
        code="E021",
        category=AnomalyCategory.REFERENTIAL,
        name="Payment Allocated to Discordant Claim",
        description="Payment record from Remittance A allocated to Claim billed to Payer B.",
        severity=SeverityLevel.HIGH,
        target_table="payments",
        target_column="claim_id",
        expected_rule_category="Referential Integrity",
        mutation_strategy="Update payments.claim_id to claim belonging to a different payer",
        expected_violation="Payment allocated to claim belonging to a different payer than remittance",
    ),
    "E022": AnomalyDefinition(
        code="E022",
        category=AnomalyCategory.REFERENTIAL,
        name="Remittance Payer Mismatch with Claim",
        description="Remittance header payer disagrees with child payment claim payer.",
        severity=SeverityLevel.HIGH,
        target_table="remittances",
        target_column="payer_id",
        expected_rule_category="Referential Integrity",
        mutation_strategy="Update remittances.payer_id to alternate payer",
        expected_violation="Remittance paying entity does not match claim adjudicated payer",
    ),

    # --------------------------------------------------------------------------
    # CATEGORY 4: FINANCIAL & RECONCILIATION DEFECTS (E023–E033)
    # --------------------------------------------------------------------------
    "E023": AnomalyDefinition(
        code="E023",
        category=AnomalyCategory.FINANCIAL,
        name="Payment Exceeds Billed Amount",
        description="Payment amount is greater than the total claim billed amount.",
        severity=SeverityLevel.CRITICAL,
        target_table="payments",
        target_column="paid_amount",
        expected_rule_category="Financial Integrity",
        mutation_strategy="Increase payments.paid_amount to total_billed_amount + 250.00",
        expected_violation="Severe overpayment anomaly: Paid > Billed",
    ),
    "E024": AnomalyDefinition(
        code="E024",
        category=AnomalyCategory.FINANCIAL,
        name="Adjustment Exceeds Remaining Balance",
        description="Contractual adjustment exceeds allowable balance after payment.",
        severity=SeverityLevel.HIGH,
        target_table="adjustments",
        target_column="adjustment_amount",
        expected_rule_category="Financial Integrity",
        mutation_strategy="Increase adjustments.adjustment_amount by 500.00",
        expected_violation="Total adjustments exceed unadjudicated claim balance",
    ),
    "E025": AnomalyDefinition(
        code="E025",
        category=AnomalyCategory.FINANCIAL,
        name="Inflated Contractual Adjustment",
        description="Contractual adjustment inflated causing negative net reimbursement balance.",
        severity=SeverityLevel.HIGH,
        target_table="adjustments",
        target_column="adjustment_amount",
        expected_rule_category="Financial Integrity",
        mutation_strategy="Inflate CO-45 adjustment by 150%",
        expected_violation="Contractual write-off exceeds fee schedule parameters",
    ),
    "E026": AnomalyDefinition(
        code="E026",
        category=AnomalyCategory.FINANCIAL,
        name="Incorrect Patient Responsibility Allocation",
        description="Patient responsibility mismatch causing unallocated remainder.",
        severity=SeverityLevel.MEDIUM,
        target_table="reconciliations",
        target_column="total_patient_resp",
        expected_rule_category="Financial Integrity",
        mutation_strategy="Add 100.00 to reconciliations.total_patient_resp",
        expected_violation="Patient copay/coinsurance out of balance with adjustments",
    ),
    "E027": AnomalyDefinition(
        code="E027",
        category=AnomalyCategory.FINANCIAL,
        name="Remittance Batch Total Mismatch",
        description="Remittance total_paid_amount differs from sum of child payments.",
        severity=SeverityLevel.CRITICAL,
        target_table="remittances",
        target_column="total_paid_amount",
        expected_rule_category="Financial Integrity",
        mutation_strategy="Add 500.00 to remittances.total_paid_amount",
        expected_violation="Remittance header total does not equal sum of itemized payments",
    ),
    "E028": AnomalyDefinition(
        code="E028",
        category=AnomalyCategory.FINANCIAL,
        name="Duplicate Payment Overdisbursement",
        description="Second identical payment allocated to claim causing cumulative overpayment.",
        severity=SeverityLevel.CRITICAL,
        target_table="payments",
        target_column="paid_amount",
        expected_rule_category="Financial Integrity",
        mutation_strategy="Double payments.paid_amount on claim",
        expected_violation="Cumulative payments exceed total billed amount",
    ),
    "E029": AnomalyDefinition(
        code="E029",
        category=AnomalyCategory.FINANCIAL,
        name="Financial Reconciliation Variance",
        description="Reconciliation ledger contains non-zero variance amount.",
        severity=SeverityLevel.CRITICAL,
        target_table="reconciliations",
        target_column="variance_amount",
        expected_rule_category="Financial Integrity",
        mutation_strategy="Set reconciliations.variance_amount = 175.50 on balanced claim",
        expected_violation="Reconciliation ledger fails zero-variance invariant",
    ),
    "E030": AnomalyDefinition(
        code="E030",
        category=AnomalyCategory.FINANCIAL,
        name="Claim Header Billed vs Line Sum Mismatch",
        description="Claim total_billed_amount differs from sum of claim_lines.",
        severity=SeverityLevel.CRITICAL,
        target_table="claims",
        target_column="total_billed_amount",
        expected_rule_category="Financial Integrity",
        mutation_strategy="Add 200.00 to claims.total_billed_amount without updating lines",
        expected_violation="Claim header billed amount does not equal sum of itemized lines",
    ),
    "E031": AnomalyDefinition(
        code="E031",
        category=AnomalyCategory.FINANCIAL,
        name="Line Billed Arithmetic Mismatch",
        description="Line billed amount differs from units * unit_price.",
        severity=SeverityLevel.HIGH,
        target_table="claim_lines",
        target_column="line_billed_amount",
        expected_rule_category="Financial Integrity",
        mutation_strategy="Add 50.00 to claim_lines.line_billed_amount",
        expected_violation="Claim line arithmetic failure: line_billed != units * unit_price",
    ),
    "E032": AnomalyDefinition(
        code="E032",
        category=AnomalyCategory.FINANCIAL,
        name="Zero-Billed Claim with Positive Payment",
        description="Claim with zero total billed amount received cash reimbursement.",
        severity=SeverityLevel.HIGH,
        target_table="claims",
        target_column="total_billed_amount",
        expected_rule_category="Financial Integrity",
        mutation_strategy="Set claims.total_billed_amount = 0.00 on paid claim",
        expected_violation="Zero-dollar billed claim received positive payment disbursement",
    ),
    "E033": AnomalyDefinition(
        code="E033",
        category=AnomalyCategory.FINANCIAL,
        name="Paid Claim with Zero Recorded Payment",
        description="Claim status is Paid but associated payment records have 0.00 or are missing.",
        severity=SeverityLevel.HIGH,
        target_table="payments",
        target_column="paid_amount",
        expected_rule_category="Financial Integrity",
        mutation_strategy="Set payments.paid_amount = 0.00 on Paid claim",
        expected_violation="Paid claim has no positive cash payment transaction recorded",
    ),

    # --------------------------------------------------------------------------
    # CATEGORY 5: TEMPORAL & CHRONOLOGICAL ANOMALIES (E034–E042)
    # --------------------------------------------------------------------------
    "E034": AnomalyDefinition(
        code="E034",
        category=AnomalyCategory.TEMPORAL,
        name="Date of Service After Submission Date",
        description="Clinical date of service occurs after claim submission date.",
        severity=SeverityLevel.HIGH,
        target_table="encounters",
        target_column="date_of_service",
        expected_rule_category="Temporal Consistency",
        mutation_strategy="Set encounters.date_of_service = claims.submission_date + 15 days",
        expected_violation="Chronological violation: DOS > Submission date",
    ),
    "E035": AnomalyDefinition(
        code="E035",
        category=AnomalyCategory.TEMPORAL,
        name="Submission Date After Adjudication Date",
        description="Claim submission date occurs after adjudication date.",
        severity=SeverityLevel.HIGH,
        target_table="claims",
        target_column="submission_date",
        expected_rule_category="Temporal Consistency",
        mutation_strategy="Set claims.submission_date = claims.adjudication_date + 10 days",
        expected_violation="Chronological violation: Submission > Adjudication date",
    ),
    "E036": AnomalyDefinition(
        code="E036",
        category=AnomalyCategory.TEMPORAL,
        name="Payment Date Before Submission Date",
        description="Payment disbursement date occurs before claim submission.",
        severity=SeverityLevel.HIGH,
        target_table="payments",
        target_column="payment_date",
        expected_rule_category="Temporal Consistency",
        mutation_strategy="Set payments.payment_date = claims.submission_date - 5 days",
        expected_violation="Chronological violation: Payment date < Submission date",
    ),
    "E037": AnomalyDefinition(
        code="E037",
        category=AnomalyCategory.TEMPORAL,
        name="Payment Date Before Adjudication Date",
        description="Payment disbursement occurs before payer adjudication decision.",
        severity=SeverityLevel.HIGH,
        target_table="payments",
        target_column="payment_date",
        expected_rule_category="Temporal Consistency",
        mutation_strategy="Set payments.payment_date = claims.adjudication_date - 3 days",
        expected_violation="Chronological violation: Payment date < Adjudication date",
    ),
    "E038": AnomalyDefinition(
        code="E038",
        category=AnomalyCategory.TEMPORAL,
        name="Remittance Date Before Adjudication Date",
        description="ERA 835 remittance generated before claim adjudication completed.",
        severity=SeverityLevel.MEDIUM,
        target_table="remittances",
        target_column="remittance_date",
        expected_rule_category="Temporal Consistency",
        mutation_strategy="Set remittances.remittance_date = claims.adjudication_date - 4 days",
        expected_violation="Chronological violation: Remittance date < Adjudication date",
    ),
    "E039": AnomalyDefinition(
        code="E039",
        category=AnomalyCategory.TEMPORAL,
        name="Denial Date Before Submission Date",
        description="Payer denial recorded prior to claim submission date.",
        severity=SeverityLevel.HIGH,
        target_table="denials",
        target_column="denial_date",
        expected_rule_category="Temporal Consistency",
        mutation_strategy="Set denials.denial_date = claims.submission_date - 7 days",
        expected_violation="Chronological violation: Denial date < Submission date",
    ),
    "E040": AnomalyDefinition(
        code="E040",
        category=AnomalyCategory.TEMPORAL,
        name="Encounter Discharge Before Date of Service",
        description="Hospitalization discharge date precedes admission date of service.",
        severity=SeverityLevel.HIGH,
        target_table="encounters",
        target_column="discharge_date",
        expected_rule_category="Temporal Consistency",
        mutation_strategy="Set encounters.discharge_date = encounters.date_of_service - 2 days",
        expected_violation="Chronological violation: Discharge date < Date of service",
    ),
    "E041": AnomalyDefinition(
        code="E041",
        category=AnomalyCategory.TEMPORAL,
        name="Future-Dated Claim Submission Event",
        description="Claim submission date recorded in the future.",
        severity=SeverityLevel.HIGH,
        target_table="claims",
        target_column="submission_date",
        expected_rule_category="Temporal Consistency",
        mutation_strategy="Set claims.submission_date = 2028-12-31",
        expected_violation="Chronological violation: Event timestamp in the future",
    ),
    "E042": AnomalyDefinition(
        code="E042",
        category=AnomalyCategory.TEMPORAL,
        name="Claim Submission Precedes Patient Date of Birth",
        description="Claim submitted for services before the patient was born.",
        severity=SeverityLevel.CRITICAL,
        target_table="claims",
        target_column="submission_date",
        expected_rule_category="Temporal Consistency",
        mutation_strategy="Set claims.submission_date = patients.date_of_birth - 365 days",
        expected_violation="Chronological violation: Service/Submission precedes patient DOB",
    ),

    # --------------------------------------------------------------------------
    # CATEGORY 6: CLAIM LIFECYCLE & FSM ANOMALIES (E043–E050)
    # --------------------------------------------------------------------------
    "E043": AnomalyDefinition(
        code="E043",
        category=AnomalyCategory.LIFECYCLE,
        name="Invalid Direct State Transition in History",
        description="Claim status history shows illegal transition (e.g. Denied -> Paid direct).",
        severity=SeverityLevel.HIGH,
        target_table="claim_status_history",
        target_column="previous_status_code",
        expected_rule_category="Lifecycle Consistency",
        mutation_strategy="Insert transition from Denied directly to Paid without Resubmitted",
        expected_violation="Illegal FSM transition bypassing mandatory workflow stages",
    ),
    "E044": AnomalyDefinition(
        code="E044",
        category=AnomalyCategory.LIFECYCLE,
        name="Paid Claim with Zero Total Paid Balance",
        description="Claim marked as Paid but financial balance shows zero paid amount.",
        severity=SeverityLevel.HIGH,
        target_table="reconciliations",
        target_column="total_paid",
        expected_rule_category="Lifecycle Consistency",
        mutation_strategy="Set reconciliations.total_paid = 0.00 on Paid claim",
        expected_violation="Claim status is Paid but total paid financial amount is 0.00",
    ),
    "E045": AnomalyDefinition(
        code="E045",
        category=AnomalyCategory.LIFECYCLE,
        name="Denied Claim with Positive Payment",
        description="Claim in terminal Denied state has active positive payment allocations.",
        severity=SeverityLevel.HIGH,
        target_table="claims",
        target_column="current_status_code",
        expected_rule_category="Lifecycle Consistency",
        mutation_strategy="Mutate status of Paid claim with payments to Denied",
        expected_violation="Claim marked Denied despite positive cash disbursement",
    ),
    "E046": AnomalyDefinition(
        code="E046",
        category=AnomalyCategory.LIFECYCLE,
        name="Rejected Claim with Payment Allocation",
        description="Claim in Rejected state has payment records.",
        severity=SeverityLevel.HIGH,
        target_table="claims",
        target_column="current_status_code",
        expected_rule_category="Lifecycle Consistency",
        mutation_strategy="Mutate status of Paid claim with payments to Rejected",
        expected_violation="Claim in front-end Rejected state contains payment transactions",
    ),
    "E047": AnomalyDefinition(
        code="E047",
        category=AnomalyCategory.LIFECYCLE,
        name="Pending Review Claim with Finalized Payment",
        description="Claim undergoing medical review has finalized cash reimbursement.",
        severity=SeverityLevel.MEDIUM,
        target_table="claims",
        target_column="current_status_code",
        expected_rule_category="Lifecycle Consistency",
        mutation_strategy="Mutate status of Paid claim to Pending",
        expected_violation="In-flight Pending claim contains premature payment disbursement",
    ),
    "E048": AnomalyDefinition(
        code="E048",
        category=AnomalyCategory.LIFECYCLE,
        name="Submitted Claim Marked Reconciled",
        description="Active unadjudicated Submitted claim marked as reconciled.",
        severity=SeverityLevel.MEDIUM,
        target_table="claims",
        target_column="is_reconciled",
        expected_rule_category="Lifecycle Consistency",
        mutation_strategy="Set is_reconciled = 1 on Submitted claim",
        expected_violation="Unadjudicated claim prematurely flagged as financially reconciled",
    ),
    "E049": AnomalyDefinition(
        code="E049",
        category=AnomalyCategory.LIFECYCLE,
        name="Paid Claim Missing Adjudication Date",
        description="Claim is in terminal Paid state without an adjudication date.",
        severity=SeverityLevel.MEDIUM,
        target_table="claims",
        target_column="adjudication_date",
        expected_rule_category="Lifecycle Consistency",
        mutation_strategy="Set adjudication_date = NULL on Paid claim",
        expected_violation="Terminal adjudicated claim missing adjudication timestamp",
    ),
    "E050": AnomalyDefinition(
        code="E050",
        category=AnomalyCategory.LIFECYCLE,
        name="Duplicate Final Status Transitions",
        description="Claim status history contains duplicate consecutive Paid entries.",
        severity=SeverityLevel.LOW,
        target_table="claim_status_history",
        target_column="new_status_code",
        expected_rule_category="Lifecycle Consistency",
        mutation_strategy="Insert duplicate Paid -> Paid transition in claim_status_history",
        expected_violation="Redundant duplicate state transition in claim audit history",
    ),

    # --------------------------------------------------------------------------
    # CATEGORY 7: BUSINESS LOGIC & OPERATIONAL INCONSISTENCIES (E051–E060)
    # --------------------------------------------------------------------------
    "E051": AnomalyDefinition(
        code="E051",
        category=AnomalyCategory.BUSINESS_LOGIC,
        name="Claim Without Service Lines",
        description="Claim header exists with positive billed amount but zero itemized lines.",
        severity=SeverityLevel.HIGH,
        target_table="claim_lines",
        target_column="claim_id",
        expected_rule_category="Business Logic",
        mutation_strategy="Delete/reassign all claim_lines for a positive-billed claim",
        expected_violation="Billed claim header exists without any itemized procedure lines",
    ),
    "E052": AnomalyDefinition(
        code="E052",
        category=AnomalyCategory.BUSINESS_LOGIC,
        name="Claim Patient Differs from Encounter Patient",
        description="Claim header patient_id discordant with linked encounter patient_id.",
        severity=SeverityLevel.CRITICAL,
        target_table="claims",
        target_column="patient_id",
        expected_rule_category="Business Logic",
        mutation_strategy="Update claims.patient_id to different patient than encounter",
        expected_violation="Discordant patient linkage between claim and clinical encounter",
    ),
    "E053": AnomalyDefinition(
        code="E053",
        category=AnomalyCategory.BUSINESS_LOGIC,
        name="Claim Provider Differs from Encounter Provider",
        description="Claim billing provider discordant with encounter attending provider.",
        severity=SeverityLevel.MEDIUM,
        target_table="claims",
        target_column="billing_provider_id",
        expected_rule_category="Business Logic",
        mutation_strategy="Update claims.billing_provider_id to different provider than encounter",
        expected_violation="Claim billing provider mismatch with encounter clinician",
    ),
    "E054": AnomalyDefinition(
        code="E054",
        category=AnomalyCategory.BUSINESS_LOGIC,
        name="Claim Submitted Outside Timely Filing Limit",
        description="Claim submission date exceeds payer timely filing limit from DOS.",
        severity=SeverityLevel.HIGH,
        target_table="claims",
        target_column="submission_date",
        expected_rule_category="Business Logic",
        mutation_strategy="Set claims.submission_date = DOS + timely_filing_days + 60 days",
        expected_violation="Claim submission exceeds payer statutory timely-filing window",
    ),
    "E055": AnomalyDefinition(
        code="E055",
        category=AnomalyCategory.BUSINESS_LOGIC,
        name="Payment Exists for In-Flight Submitted Claim",
        description="Payment transaction exists for claim still in Submitted status.",
        severity=SeverityLevel.HIGH,
        target_table="claims",
        target_column="current_status_code",
        expected_rule_category="Business Logic",
        mutation_strategy="Update status of paid claim to Submitted while keeping payment",
        expected_violation="Cash disbursement recorded against active unadjudicated claim",
    ),
    "E056": AnomalyDefinition(
        code="E056",
        category=AnomalyCategory.BUSINESS_LOGIC,
        name="Denial Record Attached to Paid Claim",
        description="Claim has status Paid but contains active denial determination record.",
        severity=SeverityLevel.HIGH,
        target_table="denials",
        target_column="claim_id",
        expected_rule_category="Business Logic",
        mutation_strategy="Insert denial record linked to an existing fully Paid claim",
        expected_violation="Contradictory denial adjudication attached to fully paid claim",
    ),
    "E057": AnomalyDefinition(
        code="E057",
        category=AnomalyCategory.BUSINESS_LOGIC,
        name="Reconciliation Marked Balanced Despite Variance",
        description="Reconciliation status is BALANCED but variance_amount != 0.00.",
        severity=SeverityLevel.CRITICAL,
        target_table="reconciliations",
        target_column="reconciliation_status",
        expected_rule_category="Business Logic",
        mutation_strategy="Set variance_amount = 250.00 while reconciliation_status = 'BALANCED'",
        expected_violation="Reconciliation status erroneously flagged BALANCED with non-zero variance",
    ),
    "E058": AnomalyDefinition(
        code="E058",
        category=AnomalyCategory.BUSINESS_LOGIC,
        name="Reconciliation Marked Unbalanced Despite Zero Variance",
        description="Reconciliation status is UNBALANCED but variance_amount = 0.00.",
        severity=SeverityLevel.MEDIUM,
        target_table="reconciliations",
        target_column="reconciliation_status",
        expected_rule_category="Business Logic",
        mutation_strategy="Set reconciliation_status = 'UNBALANCED' when variance_amount = 0.00",
        expected_violation="Reconciliation status erroneously flagged UNBALANCED with zero variance",
    ),
    "E059": AnomalyDefinition(
        code="E059",
        category=AnomalyCategory.BUSINESS_LOGIC,
        name="Service Date Outside Active Coverage Window",
        description="Encounter date of service occurs before coverage effective date.",
        severity=SeverityLevel.HIGH,
        target_table="patient_coverage",
        target_column="effective_date",
        expected_rule_category="Business Logic",
        mutation_strategy="Set patient_coverage.effective_date = DOS + 30 days",
        expected_violation="Patient lacked active policy coverage on date of service",
    ),
    "E060": AnomalyDefinition(
        code="E060",
        category=AnomalyCategory.BUSINESS_LOGIC,
        name="Inpatient Encounter with Outpatient-Only CPT Codes",
        description="Inpatient hospitalization billed exclusively with minor outpatient codes.",
        severity=SeverityLevel.LOW,
        target_table="claim_lines",
        target_column="cpt_code",
        expected_rule_category="Business Logic",
        mutation_strategy="Replace inpatient procedure codes with minor outpatient codes (99211)",
        expected_violation="Clinical procedural coding discordant with inpatient encounter type",
    ),

    # --------------------------------------------------------------------------
    # CATEGORY 8: CODE & FORMATTING ANOMALIES (E061–E067)
    # --------------------------------------------------------------------------
    "E061": AnomalyDefinition(
        code="E061",
        category=AnomalyCategory.FORMATTING,
        name="Invalid Provider NPI Checksum",
        description="Provider NPI check digit modified to fail CMS Luhn validation.",
        severity=SeverityLevel.HIGH,
        target_table="providers",
        target_column="npi",
        expected_rule_category="Format Validity",
        mutation_strategy="Flip last digit of NPI to corrupt Luhn checksum",
        expected_violation="Provider 10-digit NPI fails standard CMS Luhn checksum algorithm",
    ),
    "E062": AnomalyDefinition(
        code="E062",
        category=AnomalyCategory.FORMATTING,
        name="Malformed CPT Procedure Code",
        description="Claim line CPT code contains non-standard characters or length.",
        severity=SeverityLevel.MEDIUM,
        target_table="claim_lines",
        target_column="cpt_code",
        expected_rule_category="Format Validity",
        mutation_strategy="Set cpt_code = 'CPT99X'",
        expected_violation="Malformed non-standard CPT procedure code format",
    ),
    "E063": AnomalyDefinition(
        code="E063",
        category=AnomalyCategory.FORMATTING,
        name="Malformed ICD-10 Diagnostic Code",
        description="Diagnosis code lacks standard ICD-10 format structure.",
        severity=SeverityLevel.MEDIUM,
        target_table="encounter_diagnoses",
        target_column="icd10_code",
        expected_rule_category="Format Validity",
        mutation_strategy="Set icd10_code = 'ICD9999'",
        expected_violation="Malformed non-standard ICD-10-CM diagnostic code",
    ),
    "E064": AnomalyDefinition(
        code="E064",
        category=AnomalyCategory.FORMATTING,
        name="Malformed NUCC Taxonomy Code",
        description="Provider taxonomy code violates standard 10-character alphanumeric syntax.",
        severity=SeverityLevel.LOW,
        target_table="providers",
        target_column="taxonomy_code",
        expected_rule_category="Format Validity",
        mutation_strategy="Set taxonomy_code = 'TAX-999'",
        expected_violation="Malformed provider NUCC specialty taxonomy code",
    ),
    "E065": AnomalyDefinition(
        code="E065",
        category=AnomalyCategory.FORMATTING,
        name="Malformed Business Reference Format",
        description="Claim reference violates standard CLM-YYYY-XXXXXXX format.",
        severity=SeverityLevel.LOW,
        target_table="claims",
        target_column="claim_reference",
        expected_rule_category="Format Validity",
        mutation_strategy="Prefix claim_reference with 'INVALID_REF_'",
        expected_violation="Claim reference violates enterprise format standard",
    ),
    "E066": AnomalyDefinition(
        code="E066",
        category=AnomalyCategory.FORMATTING,
        name="Invalid Adjustment Reason Code",
        description="Adjustment record populated with non-standard reason code.",
        severity=SeverityLevel.LOW,
        target_table="adjustments",
        target_column="reason_code",
        expected_rule_category="Format Validity",
        mutation_strategy="Set adjustments.reason_code = 'NONSTD99'",
        expected_violation="Non-standard CARC adjustment reason code",
    ),
    "E067": AnomalyDefinition(
        code="E067",
        category=AnomalyCategory.FORMATTING,
        name="Malformed Facility Tax ID (TIN)",
        description="Facility TIN violates 9-digit numeric standard.",
        severity=SeverityLevel.LOW,
        target_table="facilities",
        target_column="tin",
        expected_rule_category="Format Validity",
        mutation_strategy="Set facilities.tin = '00-XXXXX'",
        expected_violation="Malformed Federal Taxpayer Identification Number format",
    ),
}


def get_anomaly_definition(code: str) -> AnomalyDefinition:
    """Retrieve anomaly definition by code."""
    if code not in TAXONOMY:
        raise KeyError(f"Unknown anomaly code '{code}'. Available codes: {sorted(TAXONOMY.keys())}")
    return TAXONOMY[code]


def get_anomalies_by_category(category: AnomalyCategory) -> List[AnomalyDefinition]:
    """Retrieve all anomaly definitions belonging to a category."""
    return [defn for defn in TAXONOMY.values() if defn.category == category]


def list_all_anomalies() -> List[AnomalyDefinition]:
    """Return all registered anomaly definitions sorted by code."""
    return [TAXONOMY[k] for k in sorted(TAXONOMY.keys())]
