"""Data structures and models for the ClaimIQ Phase 5 QA Rule Engine."""

from dataclasses import dataclass, field
from datetime import datetime
from typing import List, Dict, Optional, Any


@dataclass
class QARuleDefinition:
    """Metadata and execution specification for a QA validation rule."""
    rule_code: str
    rule_name: str
    category_code: str
    category_id: int
    dimension_code: str
    default_severity_code: str
    target_table: str
    description: str
    sql_logic: str
    anomaly_codes: List[str]
    detection_method: str = "SQL_SET"  # SQL_SET, SQL_AGGREGATE, PYTHON_VALIDATION, COMPOSITE_EVALUATOR
    target_column: Optional[str] = None
    is_active: bool = True

    def to_dict(self) -> Dict[str, Any]:
        return {
            "rule_code": self.rule_code,
            "rule_name": self.rule_name,
            "category_code": self.category_code,
            "category_id": self.category_id,
            "dimension_code": self.dimension_code,
            "default_severity_code": self.default_severity_code,
            "target_table": self.target_table,
            "target_column": self.target_column,
            "description": self.description,
            "sql_logic": self.sql_logic,
            "anomaly_codes": self.anomaly_codes,
            "detection_method": self.detection_method,
            "is_active": self.is_active,
        }


@dataclass
class QADetectionRecord:
    """A single defect/anomaly detection finding generated by a QA rule."""
    rule_code: str
    anomaly_code: str
    target_table: str
    target_record_id: int
    target_business_reference: Optional[str] = None
    target_column: Optional[str] = None
    detected_value: Optional[str] = None
    severity_code: str = "Medium"
    dimension_code: str = "Validity"
    explanation: str = ""
    detected_at: Optional[str] = None
    variance_amount: Optional[float] = None
    claim_id: Optional[int] = None

    def get_ground_truth_key(self) -> str:
        """Construct primary matching key for ground-truth comparison."""
        return f"{self.anomaly_code}|{self.target_table}|{self.target_record_id}"

    def to_dict(self) -> Dict[str, Any]:
        return {
            "rule_code": self.rule_code,
            "anomaly_code": self.anomaly_code,
            "target_table": self.target_table,
            "target_record_id": self.target_record_id,
            "target_business_reference": self.target_business_reference,
            "target_column": self.target_column,
            "detected_value": self.detected_value,
            "severity_code": self.severity_code,
            "dimension_code": self.dimension_code,
            "explanation": self.explanation,
            "detected_at": self.detected_at,
            "variance_amount": self.variance_amount,
            "claim_id": self.claim_id,
        }


@dataclass
class QARunTelemetry:
    """Execution telemetry for a single rule evaluated within a QA run."""
    rule_code: str
    records_evaluated: int
    issues_detected: int
    execution_duration_ms: int
    run_status: str = "SUCCESS"


@dataclass
class DQDimensionScore:
    """Score breakdown for one of the 7 Data Quality dimensions."""
    dimension_code: str
    dimension_name: str
    weight: float
    records_evaluated: int
    issues_detected: int
    raw_score: float
    weighted_score: float


@dataclass
class DQScoreSummary:
    """Comprehensive Data Quality Score summary for a QA execution run."""
    overall_dq_score: float
    total_records_evaluated: int
    total_issues_detected: int
    dimension_scores: Dict[str, DQDimensionScore] = field(default_factory=dict)
    severity_breakdown: Dict[str, int] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "overall_dq_score": round(self.overall_dq_score, 2),
            "total_records_evaluated": self.total_records_evaluated,
            "total_issues_detected": self.total_issues_detected,
            "dimension_scores": {
                k: {
                    "dimension_code": v.dimension_code,
                    "dimension_name": v.dimension_name,
                    "weight": v.weight,
                    "records_evaluated": v.records_evaluated,
                    "issues_detected": v.issues_detected,
                    "raw_score": round(v.raw_score, 2),
                    "weighted_score": round(v.weighted_score, 2),
                }
                for k, v in self.dimension_scores.items()
            },
            "severity_breakdown": self.severity_breakdown,
        }


@dataclass
class GroundTruthEvaluationResult:
    """Performance metrics evaluating QA detections against Phase 4 ground truth."""
    total_ground_truth_anomalies: int
    total_qa_detections: int
    true_positives: int
    false_positives: int
    false_negatives: int
    precision: float
    recall: float
    f1_score: float
    detection_rate: float
    category_metrics: Dict[str, Dict[str, Any]] = field(default_factory=dict)
    unmatched_ground_truth: List[Dict[str, Any]] = field(default_factory=list)
    unmatched_detections: List[Dict[str, Any]] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "total_ground_truth_anomalies": self.total_ground_truth_anomalies,
            "total_qa_detections": self.total_qa_detections,
            "true_positives": self.true_positives,
            "false_positives": self.false_positives,
            "false_negatives": self.false_negatives,
            "precision": round(self.precision, 4),
            "recall": round(self.recall, 4),
            "f1_score": round(self.f1_score, 4),
            "detection_rate": round(self.detection_rate, 4),
            "category_metrics": self.category_metrics,
            "unmatched_ground_truth_count": len(self.unmatched_ground_truth),
            "unmatched_detections_count": len(self.unmatched_detections),
        }
